# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Artist(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Artist - a model defined in OpenAPI

        name: The name of this Artist [Optional].
        birthday: The birthday of this Artist [Optional].
        nationality: The nationality of this Artist [Optional].
        life: The life of this Artist [Optional].
        url: The url of this Artist [Optional].
    """

    name: Optional[str] = None
    birthday: Optional[str] = None
    nationality: Optional[str] = None
    life: Optional[str] = None
    url: Optional[str] = None

Artist.update_forward_refs()
